services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: Brokkr
      MYSQL_USER: BrokkrUser
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  frontend:
    build:
      context: ./Front
    ports:
      - "4200:80"  

  backend:
    build:
      context: ./API
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=BrokkrUser
      - DB_PASSWORD=passwd
      - DB_NAME=Brokkr
    depends_on:
      - db


volumes:
  db_data: